name: CI

on:
  push:
    branches:
      - "main"
      - "development"
  pull_request:
    branches:
      - "main"
      - "development"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install dependencies
        run: npm ci
      
      - name: Install backend dependencies
        run: |
          cd backend
          npm install

      - name: Check environment variables
        run: |
          echo "NEO4J_URI is set"
          echo "NEO4J_USERNAME is set"
          echo "NEO4J_PASSWORD is set"
          echo "FIREBASE_PROJECT_ID is set"
          echo "FIREBASE_PRIVATE_KEY_ID is set"
          echo "FIREBASE_PRIVATE_KEY is set"
          echo "FIREBASE_CLIENT_EMAIL is set"
          echo "FIREBASE_CLIENT_ID is set"
          echo "FIREBASE_AUTH_URI is set"
        env:
          NEO4J_URI: ${{ secrets.NEO4J_URI }}
          NEO4J_USERNAME: ${{ secrets.NEO4J_USERNAME }}
          NEO4J_PASSWORD: ${{ secrets.NEO4J_PASSWORD }}
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          FIREBASE_PRIVATE_KEY_ID: ${{ secrets.FIREBASE_PRIVATE_KEY_ID }}
          FIREBASE_PRIVATE_KEY: ${{ secrets.FIREBASE_PRIVATE_KEY }}
          FIREBASE_CLIENT_EMAIL: ${{ secrets.FIREBASE_CLIENT_EMAIL }}
          FIREBASE_CLIENT_ID: ${{ secrets.FIREBASE_CLIENT_ID }}
          FIREBASE_AUTH_URI: ${{ secrets.FIREBASE_AUTH_URI }}

      - name: Run tests with coverage
        env:
          NEO4J_URI: ${{ secrets.NEO4J_URI }}
          NEO4J_USERNAME: ${{ secrets.NEO4J_USERNAME }}
          NEO4J_PASSWORD: ${{ secrets.NEO4J_PASSWORD }}
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          FIREBASE_PRIVATE_KEY_ID: ${{ secrets.FIREBASE_PRIVATE_KEY_ID }}
          FIREBASE_PRIVATE_KEY: ${{ secrets.FIREBASE_PRIVATE_KEY }}
          FIREBASE_CLIENT_EMAIL: ${{ secrets.FIREBASE_CLIENT_EMAIL }}
          FIREBASE_CLIENT_ID: ${{ secrets.FIREBASE_CLIENT_ID }}
          FIREBASE_AUTH_URI: ${{ secrets.FIREBASE_AUTH_URI }}
        run: npm test -- --coverage

      - name: Upload Coverage Artifact
        uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: ./coverage

      - name: Download Coverage Artifacts
        uses: actions/download-artifact@v3
        with:
          name: coverage

      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@v2.3.0
        with:
          github-token: ${{ secrets.COVERALLS_REPO_TOKEN }}
