name: CI

on:
  push:
    branches:
      - "main"
      - "development"
  pull_request:
    branches:
      - "main"
      - "development"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install dependencies
        run: npm ci
      
      - name: Install backend dependencies
        run: |
          cd backend
          npm install

      - name: Check environment variables
        run: |
          echo "NEO4J_URI is set"
          echo "NEO4J_USERNAME is set"
          echo "NEO4J_PASSWORD is set"
        env:
          NEO4J_URI: ${{ secrets.NEO4J_URI }}
          NEO4J_USERNAME: ${{ secrets.NEO4J_USERNAME }}
          NEO4J_PASSWORD: ${{ secrets.NEO4J_PASSWORD }}
    
      - name: Run tests with coverage
        env:
          NEO4J_URI: ${{ secrets.NEO4J_URI }}
          NEO4J_USERNAME: ${{ secrets.NEO4J_USERNAME }}
          NEO4J_PASSWORD: ${{ secrets.NEO4J_PASSWORD }}
        run: npm test -- --coverage

      - name: Upload Coverage Artifact
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: ./coverage

      - name: Download Coverage Artifacts
        uses: actions/download-artifact@v2
        with:
          name: coverage

      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@v2.3.0
        with:
          github-token: ${{ secrets.COVERALLS_REPO_TOKEN }}
            
  # deploy_vercel:
    # needs: [test_frontend, upload_coverage]
    # uses: ./.github/workflows/deploy_vercel.yml
    # secrets: inherit

  #test_frontend:
  #  uses: ./.github/workflows/test_frontend.yml
  #  secrets: inherit
  #test_backend:
  #  uses: ./.github/workflows/test_backend.yml
  #  secrets: inherit
