name: Run all workflows

on:
  push:
    branches:
      - "main"
      - "development"
  pull_request:
    branches:
      - "main"
      - "development"
jobs:
  #test_frontend:
  #  uses: ./.github/workflows/test_frontend.yml
  #  secrets: inherit
  #test_backend:
  #  uses: ./.github/workflows/test_backend.yml
  #  secrets: inherit
  upload_coverage:
    runs-on: ubuntu-latest
    #needs: [test_frontend]
    steps:
      - uses: actions/checkout@v4

      - name: Download Coverage Artifacts
        uses: actions/download-artifact@v2

      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@v2.3.0
        with:
          COVERALLS_REPO_TOKEN: PVE088TeMiE2YcwDT0Ymr7s7UBhbB51dF              
            
  # deploy_vercel:
    # needs: [test_frontend, upload_coverage]
    # uses: ./.github/workflows/deploy_vercel.yml
    # secrets: inherit
