name: Run all workflows

on:
  push:
    branches:
      - "main"
      # - "development"
  pull_request:
    branches:
      - "main"

jobs:
  #test_frontend:
  #  uses: ./.github/workflows/test_frontend.yml
  #  secrets: inherit
  #test_backend:
  #  uses: ./.github/workflows/test_backend.yml
  #  secrets: inherit
  upload_coverage:
    runs-on: ubuntu-latest
    #needs: [test_frontend]
    steps:
      - uses: actions/checkout@v4

      - name: Download Coverage Artifacts
        uses: actions/download-artifact@v2

      - name: upload coverage
        uses: codecov/codecov-action@v4.0.1
        with:
          files: frontend-coverage/coverage/lcov.info, backend-coverage/coverage
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: ${{ github.repository }}

  # deploy_vercel:
    # needs: [test_frontend, upload_coverage]
    # uses: ./.github/workflows/deploy_vercel.yml
    # secrets: inherit
